### ISSUE TITLE
Fails to compile with apple clang

### ISSUE THREAD

**Issue by alecjacobson** [jlblancoc/nanoflann#167]
It seems clang doesn't like variadic args after default values. 

```
In file included from /Users/ajx/Repos/kmeans/build/nanoflann/examples/pointcloud_custom_metric.cpp:32:
/Users/ajx/Repos/kmeans/build/nanoflann/include/nanoflann.hpp:1344:70: error: missing default argument on parameter 'args'
        const KDTreeSingleIndexAdaptorParams& params = {}, Args&&... args)
                                                                     ^
/Users/ajx/Repos/kmeans/build/nanoflann/examples/pointcloud_custom_metric.cpp:102:18: note: in instantiation of function template specialization
      'nanoflann::KDTreeSingleIndexAdaptor<My_Custom_Metric_Adaptor<double, PointCloud<double>, double, unsigned int>, PointCloud<double>, 3,
      unsigned int>::KDTreeSingleIndexAdaptor<const double &>' requested here
    my_kd_tree_t index(3 /*dim*/, cloud, {10 /* max leaf */}, myMetricParam);
```

I'm using

```
clang++ --version                                                                                                                          (base) 
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by alecjacobson** [comment]
FWIW v1.3.2 works. Seems like the problem started with 2baa030dde468b4544a139bf69eb9f21a7c8cb64

**Comment by jlblancoc** [comment]
Ok, I will try to replicate with a non-apple version of clang to find out the real reason of this. If someone finds it earlier, PRs are welcome! :-)

**Comment by jlblancoc** [comment]
I tried with clang-15 and it builds ok... weird.
Can you show the full compiler line ? e.g. `VERBOSE=1 make`

**Comment by BotellaA** [comment]
Same error with `gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)`
```
/XXX/include/nanoflann.hpp:1342:5: error: default argument missing for parameter 4 of ‘nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, AccessorType>::KDTreeSingleIndexAdaptor(nanoflann::KDTreeSingleIndexAdaptor<Distance, DatasetAdaptor, DIM, AccessorType>::Dimension, const DatasetAdaptor&, const nanoflann::KDTreeSingleIndexAdaptorParams&, Args&& ...)’
     KDTreeSingleIndexAdaptor(
     ^
```

cc @jruiu

**Comment by Pikecillo** [comment]
To verify that fix works with the defective versions (and later): https://godbolt.org/z/fKdxfr1Ts

**Comment by Pikecillo** [comment]
Following PR makes the project work with the defective gcc (<= 4.8.5) and clang (<=10.0.1) versions: https://github.com/jlblancoc/nanoflann/pull/176
Following Compiler Explorer instance may be helpful in verifying that the fix works with the defective version (and later): https://godbolt.org/z/zz7qrb95r
